- name: install packages
  become: true
  become_user: root
  apt:
    state: present
    name:
      - rofi
      - flameshot
      - dragon
      - arandr
      - zenity
      - pavucontrol
      - paprefs
      - openscad
      - qutebrowser
      - keepassxc

# vim: shiftwidth=2
